from application.views.dashboard import (
    dashboard,
    personal_update,
    address_update,
    sslc_update,
    hsc_update,
    academic_update,
    update_index,
    ad,
    cse,
    civil,
    ece,
    eee,
    csbs,
    mech,
    it,
    name_search,
    dip_name_search,
    export_to_excel,
    export_page,
    export_to_personal_excel,
    export_to_excel_colum,
    export_to_excel_column,
    data_changed,

    

)
from application.views.postform import (
   index,
   post_index,
   postform,
   address,
   sslc,
   hsc,
   diploma,
   academic_details,
   thankyou,
)


__all__ = [
    index,
    postform,
    post_index,
    address,
    sslc,
   hsc,
   diploma,
   academic_details,
   thankyou,
   dashboard,
    personal_update,
    address_update,
    sslc_update,
    hsc_update,
    academic_update,
    update_index,
    ad,
    cse,
    civil,
    ece,
    eee,
    csbs,
    mech,
    it,
    name_search,
    dip_name_search,
    export_to_excel,
    export_to_excel_colum,
    export_page,
    export_to_personal_excel,
    export_to_excel_column,
    data_changed
]
