from application.views.dashboard import (
    dashboard,
    personal_update,
    address_update,
    sslc_update,
    hsc_update,
    academic_update,
    update_index,
    ad,
    cse,
    civil,
    ece,
    eee,
    csbs,
    mech,
    it,
    name_search,
    dip_name_search,
    export_to_excel,
    export_page,
    export_to_personal_excel,
    export_to_excel_colum,
    export_to_excel_column,
    data_changed,
    delete,
)

from application.views.preform_dashboard import (
    preform_dashboard,
    preform_ad,
    preform_cse,
    preform_civil,
    preform_ece,
    preform_eee,
    preform_csbs,
    preform_mech,
    preform_it,
    preform_data_changed,
    student_info
    
)

from application.views.postform import (
   index,
   login,
   signup,
   post_index,
   postform,
   address,
   sslc,
   hsc,
   diploma,
   academic_details,
   thankyou,
   preview,
   pdf_check
)

from application.views.preform import (
 preform_pesonal,
 preform_hsc,
 preform_diploma,
 preform_declare,
 pre_index,

)

from application.views.post_pdf import (
 post_aca,
 post_voc,
 post_dip,
 post_dip_aca,
 post_dip_voc,

)
__all__ = [
    index,
    postform,
    login,
    signup,
    post_index,
    pdf_check,
    address,
    sslc,
   hsc,
   diploma,
   academic_details,
   thankyou,
   dashboard,
    personal_update,
    address_update,
    sslc_update,
    hsc_update,
    academic_update,
    update_index,
    ad,
    cse,
    civil,
    ece,
    eee,
    csbs,
    mech,
    it,
    name_search,
    dip_name_search,
    export_to_excel,
    export_to_excel_colum,
    export_page,
    export_to_personal_excel,
    export_to_excel_column,
    data_changed,
    delete,
    preform_pesonal,
    preform_hsc,
    preform_diploma,
    preform_declare,
    preform_dashboard,
    preform_ad,
    preform_cse,
    preform_civil,
    preform_ece,
    preform_eee,
    preform_csbs,
    preform_mech,
    preform_it,
    preform_data_changed,
    student_info,
    post_aca,
    post_voc,
    post_dip,
    post_dip_aca,
    post_dip_voc,
    preview,
    pre_index,]
