# Generated by Django 5.0.1 on 2024-01-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_preform_admission_exit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preform',
            name='admission_exit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
