# Generated by Django 4.1.2 on 2023-12-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_preform_preform_other_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preform",
            name="Department",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
