# Generated by Django 4.2.5 on 2024-04-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_preform_admission_exit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalform',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('admissionNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Date_of_Birth', models.DateField()),
                ('Quota', models.CharField(max_length=50)),
                ('Department', models.CharField(blank=True, max_length=50, null=True)),
                ('Gender', models.CharField(max_length=10)),
                ('Father_name', models.CharField(max_length=100)),
                ('Residental_Address_Line_1', models.CharField(max_length=50)),
                ('Self_Email_ID', models.CharField(max_length=50)),
                ('Self_Mobile_Number', models.CharField(max_length=15)),
                ('Father_Mobile_Number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=50)),
                ('Aadhaar_Number', models.CharField(max_length=50)),
                ('cutoffmark', models.CharField(max_length=50)),
                ('Hostel_Required', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('gm_conform', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='preform',
            name='Profile_Image',
            field=models.ImageField(blank=True, null=True, upload_to=" 'personal_profile_images/', year"),
        ),
        migrations.AlterField(
            model_name='preform',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
