# Generated by Django 4.1.2 on 2024-01-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0005_preform_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="preform",
            name="perrsonal_Image",
            field=models.ImageField(
                blank=True, null=True, upload_to="personal_profile_images/"
            ),
        ),
    ]
