# Generated by Django 5.0.1 on 2024-05-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_preform_admission_exit'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificates',
            fields=[
                ('admissionNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Quota', models.CharField(max_length=100)),
                ('admissionFor', models.CharField(max_length=100)),
                ('Tenth_mark_sheet', models.BooleanField(default=False)),
                ('eleventh_mark_sheet', models.BooleanField(default=False)),
                ('Twelfth_mark_sheet', models.BooleanField(default=False)),
                ('Transfer_Certificate', models.BooleanField(default=False)),
                ('Community_Certificate', models.BooleanField(default=False)),
                ('First_year_graduate_Certificate', models.BooleanField(default=False)),
                ('Income_Certificate', models.BooleanField(default=False)),
                ('Migration_Certificate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GQ_Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=50)),
                ('Tuition_Fees', models.CharField(max_length=50)),
                ('CoExtra_Curricularfees', models.CharField(max_length=50)),
                ('Development_fees', models.CharField(max_length=50)),
                ('Learning_Materials_Platform_UniformFees', models.CharField(max_length=50)),
                ('Caution_Deposit', models.CharField(max_length=50)),
                ('Hostel', models.CharField(blank=True, max_length=50, null=True)),
                ('Dayscholar', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MQ_Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=50)),
                ('Tuition_Fees', models.CharField(max_length=50)),
                ('CoExtra_Curricularfees', models.CharField(max_length=50)),
                ('Development_fees', models.CharField(max_length=50)),
                ('Learning_Materials_Platform_UniformFees', models.CharField(max_length=50)),
                ('Caution_Deposit', models.CharField(max_length=50)),
                ('Hostel', models.CharField(blank=True, max_length=50, null=True)),
                ('Dayscholar', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personalform',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('admissionNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('Quota', models.CharField(max_length=50)),
                ('Department', models.CharField(blank=True, max_length=50, null=True)),
                ('Gender', models.CharField(max_length=10)),
                ('Father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(max_length=50)),
                ('Mobile_Number', models.CharField(blank=True, max_length=15, null=True)),
                ('Aadhaar_Number', models.CharField(max_length=50)),
                ('cutoffmark', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('gm_conform', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='transport',
            fields=[
                ('admissionNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Bus_route', models.CharField(blank=True, max_length=100, null=True)),
                ('Bus_stop', models.CharField(blank=True, max_length=100, null=True)),
                ('Bus_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Bus_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=500)),
                ('password2', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='diplomo',
            name='education_qualified',
        ),
        migrations.AddField(
            model_name='academic_details',
            name='academic_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hsc_marks',
            name='other_Eleventh_Std_School_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hsc_marks',
            name='other_Twelfth_Std_School_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='academic_Category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='other_Tenth_Std_School_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academic_details',
            name='Branch_Code_No',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academic_details',
            name='dateadmission',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diplomo',
            name='diploma_obtain_mark',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diplomo',
            name='sem1_obtain_mark',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='diplomo',
            name='sem1_total_mark',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='diplomo',
            name='sem2_obtain_mark',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='diplomo',
            name='sem2_total_mark',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='diplomo',
            name='sem3_total_mark',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='diplomo',
            name='sem4_obtain_mark',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='diplomo',
            name='sem5_obtain_mark',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='diplomo',
            name='sem5_total_mark',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='diplomo',
            name='sem6_total_mark',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='diplomo',
            name='total_percentages',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_aca_CUT_OFF_Mark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_aca_Chemistry_Mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_aca_Elective_Mark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_aca_English_Mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_aca_Language_Mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_aca_Mathematics_Mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_aca_PCM_Average',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_aca_Physics_Mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_aca_Total_Marks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_voc_CUT_OFF_Mark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_voc_English_Mark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_voc_Language_Mark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_voc_Mathematics_or_Physics_Mark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_voc_Mathematics_or_Physics_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_voc_PCM_Average',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_voc_Practical_Mark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_voc_Total_Marks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_voc_Vocational_Theory_Mark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_voc_Vocational_Theory_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_marks',
            name='Twelfth_Std_voc_chemistry_Mark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='Guardian_Father_Mobile_No',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='preform',
            name='Profile_Image',
            field=models.ImageField(blank=True, null=True, upload_to=" 'personal_profile_images/', year"),
        ),
        migrations.AlterField(
            model_name='preform',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='preform_other_info',
            name='sem1_obtain_mark',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='preform_other_info',
            name='sem1_total_mark',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='preform_other_info',
            name='sem2_obtain_mark',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='preform_other_info',
            name='sem2_total_mark',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
