# Generated by Django 4.1.2 on 2024-01-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0006_preform_perrsonal_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="preform", old_name="perrsonal_Image", new_name="Profile_Image",
        ),
    ]
