# Generated by Django 5.0.1 on 2024-05-28 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_certificates_gq_fees_mq_fees_personalform_transport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hsc_marks',
            old_name='Twelfth_Std_Register_No',
            new_name='Twelfth_Std_Roll_No',
        ),
    ]
