# Generated by Django 5.0.1 on 2024-04-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_personalform_alter_preform_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalform',
            old_name='Hostel_Required',
            new_name='Mode',
        ),
        migrations.AlterField(
            model_name='personalform',
            name='gm_conform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
