# Generated by Django 5.0.1 on 2024-05-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_certificates_gq_fees_mq_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='Community_Certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='First_year_graduate_Certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='Income_Certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='Migration_Certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='Tenth_mark_sheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='Transfer_Certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='Twelfth_mark_sheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='eleventh_mark_sheet',
            field=models.BooleanField(default=False),
        ),
    ]
