# Generated by Django 5.0.1 on 2024-04-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_rename_hostel_required_personalform_mode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalform',
            old_name='Father_Mobile_Number',
            new_name='Mobile_Number',
        ),
        migrations.RenameField(
            model_name='personalform',
            old_name='Residental_Address_Line_1',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='personalform',
            old_name='Self_Email_ID',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='personalform',
            name='Date_of_Birth',
        ),
        migrations.RemoveField(
            model_name='personalform',
            name='Mode',
        ),
        migrations.RemoveField(
            model_name='personalform',
            name='Self_Mobile_Number',
        ),
        migrations.RemoveField(
            model_name='personalform',
            name='whatsapp_number',
        ),
    ]
