# Generated by Django 5.0.1 on 2024-04-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_rename_father_mobile_number_personalform_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GQ_Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=50)),
                ('Tuition_Fees', models.CharField(max_length=50)),
                ('CoExtra_Curricularfees', models.CharField(max_length=50)),
                ('Development_fees', models.CharField(max_length=50)),
                ('Learning_Materials_Platform_UniformFees', models.CharField(max_length=50)),
                ('Caution_Deposit', models.CharField(max_length=50)),
                ('Hostel', models.CharField(blank=True, max_length=50, null=True)),
                ('Dayscholar', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MQ_Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=50)),
                ('Tuition_Fees', models.CharField(max_length=50)),
                ('CoExtra_Curricularfees', models.CharField(max_length=50)),
                ('Development_fees', models.CharField(max_length=50)),
                ('Learning_Materials_Platform_UniformFees', models.CharField(max_length=50)),
                ('Caution_Deposit', models.CharField(max_length=50)),
                ('Hostel', models.CharField(blank=True, max_length=50, null=True)),
                ('Dayscholar', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
