# Generated by Django 5.0.1 on 2024-05-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_gq_fees_mq_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='Guardian_Father_Mobile_No',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='personalform',
            name='Father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalform',
            name='Mobile_Number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='personalform',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
