# Generated by Django 5.0.1 on 2024-05-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_academic_details_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsc_marks',
            name='other_Eleventh_Std_School_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hsc_marks',
            name='other_Twelfth_Std_School_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='other_Tenth_Std_School_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
